services:
  postgres:
    image: postgres:16-alpine
    container_name: nutri-api-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nutri
      POSTGRES_PASSWORD: nutri
      POSTGRES_DB: nutri_lab
    volumes:
      - nutri_pg_data:/var/lib/postgresql/data
      # Solo se ejecuta la primera vez que se crea el volumen
      - ./sql/001_init.sql:/docker-entrypoint-initdb.d/001_init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nutri -d nutri_lab"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 10s

volumes:
  nutri_pg_data:
